language: c++

cache:
  ccache: true

addons:
  apt:
    update: true
    packages:
      - clang
      - clang-format
      - llvm
      - llvm-dev
      - lcov
      - ruby
      - gcc-12
      - g++-12
      - golang-go

env:
  global:
    - CMAKE_C_COMPILER_LAUNCHER=ccache
    - CMAKE_CXX_COMPILER_LAUNCHER=ccache

jobs:
  include:
    - name: "Static Analysis"
      os: linux
      dist: jammy
      env:
        - CC=clang
        - CXX=clang++
      before_script:
        - cmake -DCMAKE_BUILD_TYPE=Debug -DSTATIC_ANALYSIS=ON .
      script:
        - cmake --build . --config Debug --parallel 3

    - name: "GCC Build"
      os: linux
      dist: jammy
      env:
        - CC=gcc-12
        - CXX=g++-12
      before_script:
        - cmake -DCMAKE_BUILD_TYPE=Release .
      script:
        - cmake --build . --config Release --parallel 3

    - name: "Clang Build"
      os: linux
      dist: jammy
      env:
        - CC=clang
        - CXX=clang++
      before_script:
        - cmake -DCMAKE_BUILD_TYPE=Release .
      script:
        - cmake --build . --config Release --parallel 3 --target format.check
        - cmake --build . --config Release --parallel 3

    - name: "Docker and Integration Tests"
      os: linux
      dist: jammy
      services:
        - docker
      env:
        - TAG=`if [ $TRAVIS_BRANCH == "master" ]; then echo -n latest; else echo -n $TRAVIS_BRANCH; fi`
        - BLOCK_PRODUCER_TAG=$TAG
      install:
        - git clone https://github.com/koinos/koinos-integration-tests.git
        - pushd koinos-integration-tests
        - go get ./...
        - popd
      before_script:
        - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        - cp -R ~/.ccache ./ccache
        - docker build . -t build --target builder
        - docker build . -t $TRAVIS_REPO_SLUG:$TAG
        - docker run -td --name extract-ccache build
        - docker cp extract-ccache:/build/.ccache ~/.ccache
      script:
        - pushd koinos-integration-tests
        - ./run.sh
      after_success:
        - |
          if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
            docker push $TRAVIS_REPO_SLUG:$TAG
          fi

notifications:
  slack:
    secure: ILGZYlZLDN5DxShH8znBeX8klW6IS6l1YWoZspGI776d5/7Ye007tksVji+MYJ1VZW1Au7r4d44aNBVAX+YjZivS1SC/5sEu2GalhULNrjx1No1maUMr2eqx6aoZku0UyhnfiI+kzKE3dv2Yadf/DQzzggXyU+Du9BiP8+xWV8rmlIlgYmaPcaBTGOTIp3kFd1FsV6X42rB6SJk47g/uaVukZ5+B2t3WC9y5y+vBfGw+q6K2MRXLqoOlaKIvfxCUTpATEE1LhkRRISO7/XfEyMbZWMYf/YUCS91c6EAsn0APuCnmNvpzxySGu9Bn77fPXDjgCeJmKJsuOmp5c/WFNJGyZx4Qoy9ZSpLs5fJa9p+t0RK2IMlCvzk0RwaBWeNN37ujnrQ21d7LopVsqDbzGMl5DNXTbX/sLUJ+tPmjfeXQcxuKkzeqd1BPLKOjMuzMwUX6v1ard+7PiqEyPOjruUFYI5DATRR2wUlxgc5eIUOCd0e/nUqFlUKFQwnRp0Mz361uPGGoQF6cLPL+NjBcXIHGcCh1G++CBdStNk5kcKRGgcLfM5zcaPaFl87yMPJSazpowo88rWWDi6fZsbtiPt3Y/sSX5+2+0P3XAK4p9Fuhfv9532PuSco57TxeCEuZ6bTTitlVkoTtfPvZFmK4SuF206GoFvbOSR+DImv5VZs=
    on_success: never
